# Generated by Django 5.0.1 on 2024-01-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField(max_length=10)),
                ('uname', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('cpassword', models.CharField(max_length=12)),
            ],
        ),
    ]
